name: campers_closet
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  google_fonts: ^8.0.2
  smooth_page_indicator: ^2.0.1
  exui: ^1.0.11
  pinput: ^6.0.2
  carousel_slider: ^5.1.2
  flutter_inner_shadow: ^0.0.1
  cached_network_image: ^3.4.1
  dropdown_flutter: ^1.0.3
  modal_bottom_sheet: ^3.0.0
  intl: ^0.20.2
  camera: ^0.12.0
  permission_handler: ^12.0.1
  dio: ^5.9.2
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
